/* eslint-disable */
import * as types from './graphql';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "query CollectionList($channel: String!, $languageCode: LanguageCodeEnum!) {\n  collections(first: 100, channel: $channel) {\n    edges {\n      node {\n        id\n        name\n        slug\n        description\n        translation(languageCode: $languageCode) {\n          name\n          description\n        }\n        backgroundImage {\n          url\n          alt\n        }\n        products(first: 100) {\n          edges {\n            node {\n              ...ProductListItem\n            }\n          }\n        }\n      }\n    }\n  }\n}": typeof types.CollectionListDocument,
    "fragment MenuItem on MenuItem {\n  id\n  name\n  level\n  translation(languageCode: $languageCode) {\n    id\n    name\n  }\n  category {\n    id\n    slug\n    name\n    translation(languageCode: $languageCode) {\n      name\n    }\n  }\n  collection {\n    id\n    name\n    slug\n    translation(languageCode: $languageCode) {\n      name\n    }\n  }\n  page {\n    id\n    title\n    slug\n    translation(languageCode: $languageCode) {\n      title\n    }\n  }\n  url\n}\n\nfragment MenuItemNested on MenuItem {\n  ...MenuItem\n  children {\n    ...MenuItem\n    children {\n      ...MenuItem\n      children {\n        ...MenuItem\n        children {\n          ...MenuItem\n          children {\n            ...MenuItem\n            children {\n              ...MenuItem\n            }\n          }\n        }\n      }\n    }\n  }\n}\n\nquery MenuGetBySlug($slug: String!, $channel: String!, $languageCode: LanguageCodeEnum = EN) {\n  menu(slug: $slug, channel: $channel) {\n    items {\n      ...MenuItemNested\n    }\n  }\n}": typeof types.MenuItemFragmentDoc,
    "query ProductListByCollectionPaginated($slug: String!, $channel: String!, $languageCode: LanguageCodeEnum!, $first: Int!, $after: String) {\n  collection(slug: $slug, channel: $channel) {\n    name\n    description\n    seoDescription\n    seoTitle\n    translation(languageCode: $languageCode) {\n      name\n      description\n      seoDescription\n      seoTitle\n    }\n    products(\n      first: $first\n      after: $after\n      sortBy: {field: COLLECTION, direction: ASC}\n    ) {\n      totalCount\n      edges {\n        node {\n          ...ProductListItem\n        }\n        cursor\n      }\n      pageInfo {\n        endCursor\n        hasNextPage\n      }\n    }\n  }\n}": typeof types.ProductListByCollectionPaginatedDocument,
    "fragment ProductListItem on Product {\n  id\n  name\n  slug\n  translation(languageCode: $languageCode) {\n    name\n  }\n  pricing {\n    priceRange {\n      start {\n        gross {\n          amount\n          currency\n        }\n      }\n      stop {\n        gross {\n          amount\n          currency\n        }\n      }\n    }\n  }\n  category {\n    id\n    name\n    translation(languageCode: $languageCode) {\n      name\n    }\n  }\n  productType {\n    id\n    name\n  }\n  thumbnail(size: 1024, format: WEBP) {\n    url\n    alt\n  }\n  variants {\n    id\n    name\n    quantityAvailable\n    translation(languageCode: $languageCode) {\n      name\n    }\n  }\n  defaultVariant {\n    id\n    quantityAvailable\n  }\n}": typeof types.ProductListItemFragmentDoc,
};
const documents: Documents = {
    "query CollectionList($channel: String!, $languageCode: LanguageCodeEnum!) {\n  collections(first: 100, channel: $channel) {\n    edges {\n      node {\n        id\n        name\n        slug\n        description\n        translation(languageCode: $languageCode) {\n          name\n          description\n        }\n        backgroundImage {\n          url\n          alt\n        }\n        products(first: 100) {\n          edges {\n            node {\n              ...ProductListItem\n            }\n          }\n        }\n      }\n    }\n  }\n}": types.CollectionListDocument,
    "fragment MenuItem on MenuItem {\n  id\n  name\n  level\n  translation(languageCode: $languageCode) {\n    id\n    name\n  }\n  category {\n    id\n    slug\n    name\n    translation(languageCode: $languageCode) {\n      name\n    }\n  }\n  collection {\n    id\n    name\n    slug\n    translation(languageCode: $languageCode) {\n      name\n    }\n  }\n  page {\n    id\n    title\n    slug\n    translation(languageCode: $languageCode) {\n      title\n    }\n  }\n  url\n}\n\nfragment MenuItemNested on MenuItem {\n  ...MenuItem\n  children {\n    ...MenuItem\n    children {\n      ...MenuItem\n      children {\n        ...MenuItem\n        children {\n          ...MenuItem\n          children {\n            ...MenuItem\n            children {\n              ...MenuItem\n            }\n          }\n        }\n      }\n    }\n  }\n}\n\nquery MenuGetBySlug($slug: String!, $channel: String!, $languageCode: LanguageCodeEnum = EN) {\n  menu(slug: $slug, channel: $channel) {\n    items {\n      ...MenuItemNested\n    }\n  }\n}": types.MenuItemFragmentDoc,
    "query ProductListByCollectionPaginated($slug: String!, $channel: String!, $languageCode: LanguageCodeEnum!, $first: Int!, $after: String) {\n  collection(slug: $slug, channel: $channel) {\n    name\n    description\n    seoDescription\n    seoTitle\n    translation(languageCode: $languageCode) {\n      name\n      description\n      seoDescription\n      seoTitle\n    }\n    products(\n      first: $first\n      after: $after\n      sortBy: {field: COLLECTION, direction: ASC}\n    ) {\n      totalCount\n      edges {\n        node {\n          ...ProductListItem\n        }\n        cursor\n      }\n      pageInfo {\n        endCursor\n        hasNextPage\n      }\n    }\n  }\n}": types.ProductListByCollectionPaginatedDocument,
    "fragment ProductListItem on Product {\n  id\n  name\n  slug\n  translation(languageCode: $languageCode) {\n    name\n  }\n  pricing {\n    priceRange {\n      start {\n        gross {\n          amount\n          currency\n        }\n      }\n      stop {\n        gross {\n          amount\n          currency\n        }\n      }\n    }\n  }\n  category {\n    id\n    name\n    translation(languageCode: $languageCode) {\n      name\n    }\n  }\n  productType {\n    id\n    name\n  }\n  thumbnail(size: 1024, format: WEBP) {\n    url\n    alt\n  }\n  variants {\n    id\n    name\n    quantityAvailable\n    translation(languageCode: $languageCode) {\n      name\n    }\n  }\n  defaultVariant {\n    id\n    quantityAvailable\n  }\n}": types.ProductListItemFragmentDoc,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query CollectionList($channel: String!, $languageCode: LanguageCodeEnum!) {\n  collections(first: 100, channel: $channel) {\n    edges {\n      node {\n        id\n        name\n        slug\n        description\n        translation(languageCode: $languageCode) {\n          name\n          description\n        }\n        backgroundImage {\n          url\n          alt\n        }\n        products(first: 100) {\n          edges {\n            node {\n              ...ProductListItem\n            }\n          }\n        }\n      }\n    }\n  }\n}"): typeof import('./graphql').CollectionListDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment MenuItem on MenuItem {\n  id\n  name\n  level\n  translation(languageCode: $languageCode) {\n    id\n    name\n  }\n  category {\n    id\n    slug\n    name\n    translation(languageCode: $languageCode) {\n      name\n    }\n  }\n  collection {\n    id\n    name\n    slug\n    translation(languageCode: $languageCode) {\n      name\n    }\n  }\n  page {\n    id\n    title\n    slug\n    translation(languageCode: $languageCode) {\n      title\n    }\n  }\n  url\n}\n\nfragment MenuItemNested on MenuItem {\n  ...MenuItem\n  children {\n    ...MenuItem\n    children {\n      ...MenuItem\n      children {\n        ...MenuItem\n        children {\n          ...MenuItem\n          children {\n            ...MenuItem\n            children {\n              ...MenuItem\n            }\n          }\n        }\n      }\n    }\n  }\n}\n\nquery MenuGetBySlug($slug: String!, $channel: String!, $languageCode: LanguageCodeEnum = EN) {\n  menu(slug: $slug, channel: $channel) {\n    items {\n      ...MenuItemNested\n    }\n  }\n}"): typeof import('./graphql').MenuItemFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query ProductListByCollectionPaginated($slug: String!, $channel: String!, $languageCode: LanguageCodeEnum!, $first: Int!, $after: String) {\n  collection(slug: $slug, channel: $channel) {\n    name\n    description\n    seoDescription\n    seoTitle\n    translation(languageCode: $languageCode) {\n      name\n      description\n      seoDescription\n      seoTitle\n    }\n    products(\n      first: $first\n      after: $after\n      sortBy: {field: COLLECTION, direction: ASC}\n    ) {\n      totalCount\n      edges {\n        node {\n          ...ProductListItem\n        }\n        cursor\n      }\n      pageInfo {\n        endCursor\n        hasNextPage\n      }\n    }\n  }\n}"): typeof import('./graphql').ProductListByCollectionPaginatedDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment ProductListItem on Product {\n  id\n  name\n  slug\n  translation(languageCode: $languageCode) {\n    name\n  }\n  pricing {\n    priceRange {\n      start {\n        gross {\n          amount\n          currency\n        }\n      }\n      stop {\n        gross {\n          amount\n          currency\n        }\n      }\n    }\n  }\n  category {\n    id\n    name\n    translation(languageCode: $languageCode) {\n      name\n    }\n  }\n  productType {\n    id\n    name\n  }\n  thumbnail(size: 1024, format: WEBP) {\n    url\n    alt\n  }\n  variants {\n    id\n    name\n    quantityAvailable\n    translation(languageCode: $languageCode) {\n      name\n    }\n  }\n  defaultVariant {\n    id\n    quantityAvailable\n  }\n}"): typeof import('./graphql').ProductListItemFragmentDoc;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
